# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

In [ ]:
boolean，布尔值，逻辑函数。当结果正确时输出TRUE，反之输出FALSE
float，浮点型，一种数据类型。
int，整数型，一种数据类型。

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [1]:
sum_1=0
sum_2=0
for i in range(100):
    if i%2 != 0:
        sum_1 += i
    else:
        sum_2 += i
sum=sum_1-sum_2
sum
    

50

1.3  将字符串 s="yoyo" 转换成列表

In [3]:
list=[]
for i in 'yoyo':
    list.append(i)
list


['y', 'o', 'y', 'o']

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

In [ ]:
在1-100当中选取最后10个

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [52]:
import pandas as pd
import numpy as np
import talib as ta
from datetime import datetime
stock1 = pd.read_excel('sz50.xlsx',sheetname='600036.XSHG', index_col='datetime')
d=pd.DataFrame(stock1)


c = np.array(d)


print(type(c))
print(ta.EMA(stock1.close.values,10)[-5:])


<class 'numpy.ndarray'>
[108.92453521 109.34734699 109.8532839  111.19632319 113.12790079]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [63]:
import pandas as pd
from datetime import datetime
data_dict={}
for i in ['600029.XSHG','600050.XSHG','601318.XSHG']:
    stock=pd.read_excel('sz50.xlsx',sheetname=i,index_col='datetime')
    data_dict[i]=data.loc['2017-01-01':'2018-01-01']
    PN = pd.Panel(data_dict)
    print(PN)
  

<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 212 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 600029.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 212 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 600050.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume
<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 212 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [4]:
class stock:
    def __init__(self,stockName,highPrice,lowPrice):
        self.stockName=stockName
        self.highPrice=highPrice
        self.lowPrice = lowPrice
    def calAmount(self):
        return {self.stockName+'_dif': self.highPrice-self.lowPrice}

stockone = stock('one',15,7)
print(stockone.calAmount())

stocktwo = stock('Two', 66, 20)
print(stocktwo.calAmount())

{'one_dif': 8}
{'Two_dif': 46}


3.5 建立一个5*5的矩阵，值从0到24

In [50]:
import numpy as np

array1=np.arange(0,25).reshape(5,5)
print(array1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
